services:
  artriapp-db:
    restart: unless-stopped
    container_name: "artriapp-db-development"
    image: postgres:16
    environment:
      - POSTGRES_USER=artriapp
      - POSTGRES_PASSWORD=artriapp
      - POSTGRES_DB=artriapp
    volumes:
      - artriapp-db:/var/lib/postgresql/data/
    ports:
      - "5438:5432"
    networks:
      - artriapp-network
    # Adicionado: Ensina o Docker a testar se o Postgres está pronto para uso
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U artriapp -d artriapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  artriapp-cache:
    restart: unless-stopped
    container_name: "artriapp-cache-development"
    image: redis:7
    volumes:
      - artriapp-cache:/data
    ports:
      - "6388:6379"
    # Adicionado: Coloca a cache na mesma rede do Django
    networks:
      - artriapp-network

  artriapp-django:
    restart: unless-stopped
    container_name: "artriapp-development"
    build:
      context: ..
      dockerfile: ./docker/django/django.Dockerfile
      args:
        ENV: local
    entrypoint: ["bash", "./docker/bin/deploy.sh"]
    env_file:
      - ./django/artriapp.env
    volumes:
      - ..:/opt/artriapp/
    depends_on:
      artriapp-db:
        condition: service_healthy
      artriapp-cache:
        condition: service_started
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - artriapp-network

volumes:
  artriapp-db:
  artriapp-cache:
  artriapp-django:
    driver: local

networks:
  artriapp-network:
    driver: bridge